### PR TITLE
Show top free places

### PR DESCRIPTION
**Pull request by VojtaStanek**
Chtěl jsem udělat jednodušší use-case "jaké si mám vybrat očkovací místo".

### CODE REVIEW

**Comment by msusicky** [comment]
Thanks, I will test it today, I have one remark. Unfortunately the process is not so simple and you cannot say that the place with most free slots is the best one. We don't like to confuse people so it is necessary to offer a proper wording and maybe to add more criterias to find the best place.
My idea: add number of vaccinated peoples in last 7 days, free vaccines (new calculation will be done today, the current one is a little bit delayed) and number of people in the queue.

**Comment by VojtaStanek** [comment]
My aim was to make it as easy as possible to tell in which place I will be probably vaccinated first. 

If I understand you correctly "free spots" include spots which might not be accessible because there is someone else "in queue" (someone else has PIN2 to this place or is waiting to get one). Number of these people is known (at least approximately; it's shown on the place page). 

Based on this I would propose calculating a metric as `people waiting / free spots` ("Poměr počtu čekajících lidí na volná místa") and sorting places by it. The number might not be precise or fully understandable for people, but it would be good quick indication which place to show. Nonetheless it would be good to explain how it's calculated.

**Comment by jan-stanek** [comment]
Yes, they might not be accessible for you, because someone else has higher priority or the center doesn't have enough vaccines. E.g. center creates 200 slots per day, but they don't have enough vaccines, so they allow only 100 people to choose a time slot.

It's not the same for all centers, good examle could be: https://ockovani.opendatalab.cz/misto/9cf6f860-3089-4f8b-abf9-86109580dd7e (probably new center, almost no vaccines / vaccinated people / people in queue, but lot of free slots).

Now we want to add another column with count of people in queue and ratio of successful reservations (registered in last 7 days and were able to choose a slot).

Another good metric could be average waiting time - but it requires additional computation and historization of fetched data (#90)

**Comment by msusicky** [comment]
As it was discussed above - free slots are confusing so we've switched to vaccination speed / queues. Sorry for that, but we are still open to any collaboration.

**Pull request closed without merging**
