### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by ara686**
FIx volumes for docker db container.
Now is persistent volume in this configuration.

### CODE REVIEW

**Comment by jan-stanek** [comment]
@ara686 thanks for the PR!

@vpokorny seems to be fine for me, it's described also here: https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes

**Comment by vpokorny** [comment]
Since yesterday I have been digging deeper into this topic. It is not that simple like just changing the folder (from `/var/lib/postgresql` to `/var/lib/postgresql/data`) to which volume is mapped inside the container, because of the possibility to lose data. 

Firstly - data are not persistent at the moment, because if you call
`docker-compose up` will spin up a container for a database that will create two volumes. The first volume is named according to the `docker-compose.yml` file like `<repo_name>_db_data` and it is mapped to the `/var/lib/postgresql`. Unfortunately there is a second volume created that is mapped to the `/var/lib/postgresql/data`. The second volume name is just a hash. Let me explain with the following commands.

Firstly inspection of running database container in my case called `ockovani_db`:
```
$ docker inspect ockovani_db
...
        "Mounts": [
            {
                "Type": "volume",
                "Name": "ockovani-covid_db_data",
                "Source": "/var/lib/docker/volumes/ockovani-covid_db_data/_data",
                "Destination": "/var/lib/postgresql",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "f685c1ccd15f31149ac7d32367760cb5196ed85b26ba31eda8789733c1685f08",
                "Source": "/var/lib/docker/volumes/f685c1ccd15f31149ac7d32367760cb5196ed85b26ba31eda8789733c1685f08/_data",
                "Destination": "/var/lib/postgresql/data",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
...
```
So there are two volumes, the first `ockovani-covid_db_data` and the second `f685c1ccd15f31149ac7d32367760cb5196ed85b26ba31eda8789733c1685f08`. In the end, in the container `ockovani-covid_db_data` there is only a directory `data` which is empty, because rest of the files are in the second container `f685c1ccd15f31149ac7d32367760cb5196ed85b26ba31eda8789733c1685f08`. Luckily in case you call `docker-compose rm` it will not remove the second container, but if you spin up the stack again with `docker-compose up` it will create a new "second" container that does not contain your downloaded data. Therefore you will endup with empty database.

My proposal to overcome data loss in this case the data from the second container (in my case `f685c1ccd15f31149ac7d32367760cb5196ed85b26ba31eda8789733c1685f08` needs to be copied with the appropriate rights to the volume `ockovani-covid_db_data` and after that you can change the mount point in `docker-compose.yml` file. The commands to accomplish this are the following.
1. Spin up the stack
```
docker-compose up
```
2. Find for persistent volume name and for temporary data volume names:
```
docker inspect <database_container_name>
...
        "Mounts": [
            {
                "Type": "volume",
                "Name": "ockovani-covid_db_data",
                "Source": "/var/lib/docker/volumes/ockovani-covid_db_data/_data",
                "Destination": "/var/lib/postgresql",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "f685c1ccd15f31149ac7d32367760cb5196ed85b26ba31eda8789733c1685f08",
                "Source": "/var/lib/docker/volumes/f685c1ccd15f31149ac7d32367760cb5196ed85b26ba31eda8789733c1685f08/_data",
                "Destination": "/var/lib/postgresql/data",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
...
```
In this case persistent volume name is `ockovani-covid_db_data` and the temp. data volume name is `f685c1ccd15f31149ac7d32367760cb5196ed85b26ba31eda8789733c1685f08`.

3. Stop and remove the stack
```
docker-compose stop
docker-compose rm
```
4. Spin up a new container to which we will mount both volumes.
```
$ docker run -ti -v f685c1ccd15f31149ac7d32367760cb5196ed85b26ba31eda8789733c1685f08:/second -v ockovani-covid_db_data:/first python:3.7 /bin/bash
#  rm -r /first/data/
# cp -rp /second/* /first/.
# ls -al /first
total 132
drwxr-xr-x 19  999  999  4096 Mar 14 22:31 .
drwxr-xr-x  1 root root  4096 Mar 14 22:29 ..
-rw-------  1  999  999     3 Mar 13 13:29 PG_VERSION
drwx------  7  999  999  4096 Mar 13 13:38 base
drwx------  2  999  999  4096 Mar 14 21:01 global
drwx------  2  999  999  4096 Mar 13 13:29 pg_commit_ts
drwx------  2  999  999  4096 Mar 13 13:29 pg_dynshmem
-rw-------  1  999  999  4535 Mar 13 13:29 pg_hba.conf
-rw-------  1  999  999  1636 Mar 13 13:29 pg_ident.conf
drwx------  4  999  999  4096 Mar 14 21:05 pg_logical
drwx------  4  999  999  4096 Mar 13 13:29 pg_multixact
drwx------  2  999  999  4096 Mar 14 21:00 pg_notify
drwx------  2  999  999  4096 Mar 13 13:29 pg_replslot
drwx------  2  999  999  4096 Mar 13 13:29 pg_serial
drwx------  2  999  999  4096 Mar 13 13:29 pg_snapshots
drwx------  2  999  999  4096 Mar 14 21:09 pg_stat
drwx------  2  999  999  4096 Mar 14 21:09 pg_stat_tmp
drwx------  2  999  999  4096 Mar 13 13:29 pg_subtrans
drwx------  2  999  999  4096 Mar 13 13:29 pg_tblspc
drwx------  2  999  999  4096 Mar 13 13:29 pg_twophase
drwx------  3  999  999  4096 Mar 14 20:58 pg_wal
drwx------  2  999  999  4096 Mar 13 13:29 pg_xact
-rw-------  1  999  999    88 Mar 13 13:29 postgresql.auto.conf
-rw-------  1  999  999 26588 Mar 13 13:29 postgresql.conf
-rw-------  1  999  999    36 Mar 14 21:00 postmaster.opts
-rw-------  1  999  999    94 Mar 14 21:08 postmaster.pid
# exit
```
5. Change volume mountpoint in the `docker-compose.yml` = download changes after this request will be merged and spin up stack again.
```
docker-compose up
```

Can this be described in the documentation in README.md file?

**Comment by jan-stanek** [comment]
If I understand it correctly, current data will not be accessible after the change? It shouldn't be a big problem since docker is not used in producation / acceptance environment, just for the development and you can always fetch new data.

**Comment by vpokorny** [comment]
Current data will be accessible when you copy them to the persistent volume `db_data` according to the guide I have provided in the comment. The point of investigating the solution was that we are storing everyday imports separately because there can be modifications in historical data. That was the motivation not to lose the data that have been downloaded already.

**Comment by vpokorny** [comment]
Of course, in case you do not need the historical data, you can just delete the volume `<repository_name>_db_data` that has been created by docker-compose. It is important that you delete this volume because there is a directory `data` that  can cause a trouble.

**Comment by jan-stanek** [comment]
@vpokorny Yes, we store them, but if you don't fetch new data in dev every day they are incomplete anyway. You are probably the only one who is using docker right now, so it's up to you :)

**Comment by vpokorny** [comment]
@jan-stanek If I am the only one using docker then it is solved, because I have already migrated my data.

**Review by vpokorny — APPROVED** [review]
Valid point, this fixes the bug with persisting data.

**Pull request merged**
