### PR TITLE
Develop docker compose

### PR DESCRIPTION
**Pull request by fernflower**

### CODE REVIEW

**Comment by jan-stanek** [comment]
Thanks! I'll take a look at it

**Comment by fernflower** [comment]
Rebased against develop

**Comment by jan-stanek** [comment]
Sometimes the application starts writing data before the postgres is fully started. Please add something like this to the beginning of the entrypoint.sh:
```
while !</dev/tcp/db/5432; do sleep 1; done;
```

Please set postgres timezone to have correct time of the last update.

@msusicky before executing it, check if you don't have CRLF in the entrypoint.sh

**Comment by fernflower** [comment]
> Sometimes the application starts writing data before the postgres is fully started. Please add something like this to the beginning of the entrypoint.sh:
> 
> ```
> while !</dev/tcp/db/5432; do sleep 1; done;
> ```
Not an issue anymore on my machine after you switched the data fetcher. Can you still reproduce it after super clean start with `FETCH_DATA=true docker-compose up --build -V`? 

> Please set postgres timezone to have correct time of the last update.
Setting the postgres timezone won't help as you are using datetime.today() in the code which is doing the guessing. I workarounded this by setting the expected timezone in the app container.

**Comment by fernflower** [comment]
Rebased against develop, could you please re-review?

**Comment by jan-stanek** [comment]
The problem occurs in migrations, fetcher is probably ok, because it starts with downloading of some big file, so postgres has enough time to start.

**Comment by fernflower** [comment]
> The problem occurs in migrations, fetcher is probably ok, because it starts with downloading of some big file, so postgres has enough time to start.

Sorry, don;t get it - do you still see the problem after `FETCH_DATA=true docker-compose up --build -V`?
Could you please post a trace of it?

application container should start strictly after db is up and running because of depends_on specified https://github.com/fernflower/ockovani-covid/blob/develop-docker-compose/docker-compose.yml#L20

**Comment by fernflower** [comment]
Hmm actually it makes sense as depends_on doesn't wait till db is ready. Ok, thanks, I will think of some nice way to check readiness.

**Comment by fernflower** [comment]
Should be fine now. Rebased against develop, please review.

**Comment by jan-stanek** [comment]
Works fine, thanks!

**Review by jan-stanek — APPROVED** [review]

**Pull request merged**
