### PR TITLE
Introduce docker-compose setup for dev environment

### PR DESCRIPTION
**Pull request by fernflower**
A single docker-compose up command brings up the deployment.
Not suitable for production as development flask server is used,
should switch to nginx (or any other real webserver) to be prod-ready.

[Still to be done before PR merge] Fill in the DB with default data while
not violating the "don't scrape the real system" policy.

### CODE REVIEW

**Comment by fernflower** [comment]
@msusicky @jan-stanek @vpokorny can you point me to the db backups I can use to prefill the db? That's the only piece I am missing. Thank you, that's a really useful project you started!

**Comment by jan-stanek** [comment]
Thanks! Here is the latest dump: 
[ockovani-2103020753.zip](https://github.com/msusicky/ockovani-covid/files/6066905/ockovani-2103020753.zip)

**Comment by msusicky** [comment]
> A single docker-compose up command brings up the deployment.
> Not suitable for production as development flask server is used,
> should switch to nginx (or any other real webserver) to be prod-ready.

Just for the clarification -> we have application server somewhere and our goal is to produce static pages. (performance reasons) We don't like to allow users to touch our app. server directly ;)

**Comment by fernflower** [comment]
> > A single docker-compose up command brings up the deployment.
> > Not suitable for production as development flask server is used,
> > should switch to nginx (or any other real webserver) to be prod-ready.
> 
> Just for the clarification -> we have application server somewhere and our goal is to produce static pages. (performance reasons) We don't like to allow users to touch our app. server directly ;)

Hmm I was writing this comment basically to indicate that docker-compose setup is only for development, not to be deployed on production (the details of deployment, especially once it's been automated is the first thing you forget so I specifically put that warning in the git comment). I can change it or remove completely, it's up to you.
BTW, are you ok with the implementation, does it work for you?

**Comment by msusicky** [comment]
It has WIP in the header. Right now we are switching to official data and it has the highest priority for us. If it is ready, please remove WIP and we will check it.
Thanks for contributing!

**Comment by fernflower** [comment]
@msusicky sure, would you like me to rebase against feature-official-data branch?

**Comment by msusicky** [comment]
Yes please, it will be great !

**Comment by fernflower** [comment]
> Yes please, it will be great ! / you can use merged develop.

Sure, thanks! Something tells me I will need a new backup to rollout as well - can you please share one?

**Comment by jan-stanek** [comment]
Now it's easy, just migrate database to the new schema using `flask db upgrade` and fetch data using `flask fetch-opendata`, no special config is needed.

**Comment by fernflower** [comment]
@msusicky Created a PR against develop https://github.com/msusicky/ockovani-covid/pull/93. 
I guess this one can be closed now.

**Pull request closed without merging**
